@Restaurants.API_HostAddress = https://localhost:7191
@Token = CfDJ8E7t732Ktx1NiejmLG_uPm0v93lePT3F-Hwfj3TsrG0snWYAMO3BTHI_f3yrpnARGQG-MaK50UlR_GJA1D4j9Gq5-loicwcY8akYhoF4ckClAgOhpLbURW_R142O88Z1mw_EqSTFX8kUu3DDgA6yZLMgEnaMsnORP9GEe4WoPDAagq2r1Iby4CJpspcg6eRClHvmQUr2RwesR-epz7G6IkckTSjwzqlG_LZ4aQ-jkcHfZ15P-VtzNfTac4OqBSMzHjwQtorDkkldw-6LbYqJ0hSmCAu2bzRKoRdptHJJseOniC-yunmsFcX7f3KgnEJv_TJztjMo0fiUaX6QsNrw2bVpOsS3-FgNPWIaiBnORNNd5I5wbRggv0vFgTyKcNsbTpECWjhePO3OrKwpxMqrW7mGPhbU-N4XzvvgUK7z5ecsEVmtj33zRSykvbpLuQ6886PfaUltdnXRmjj9BKoXUPTJXqRuz2cyTHCigoWgMehd1-uy5gQ9gyrqrFuwnfiApuDdhfmOtceVjnFRQGGIIT-gdtPQA51-zFpBw3wnH-cJZ6aHGgZ_hcWHAwzfHxEAi6x8DOQ02u8oIwf0vIFMvAy6dlHnFYvB6hzyrPrSS82tNK3dZ9FhfjJn-8wnFhAEAZJNpYqxOhkATWvtM0-LwZU9Zuumjm4_KoZlVXk3W68wwPy-0qbiLjqH2pa2set4Vv89GWkC-AZXhxyJGWOnuG9E_zRkG4tAUVelB-JDci85w-LWTYOwTZcuQlx7aRX9rybb8gBRLP1vztTP5hUQb0AuRPXzCKnWHFHGLZ_xTSAS

GET {{Restaurants.API_HostAddress}}/weatherforecast

###

POST {{Restaurants.API_HostAddress}}/weatherforecast/generate?nbResult=10
Content-Type: application/json

{
  "Min" : 4,
  "Max": 41
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants?SearchPhrase=&pageSize=5&pageNumber=1&sortBy=Name&sortDirection=Ascending
Authorization: Bearer {{Token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "Name": "Le Gourmet Françaiss",
    "Description": "Un restaurant chic offrant une expérience culinaire française authentique avec des ingrédients frais et locaux.",
    "Category": "Italian",
    "HasDelivery": false,
    "ContactEmail": "contact@legourmetfrancais.com",
    "ContactNumber": "+33 1 23 45 67 89",
    "City": "Paris",
    "Street": "123 Rue de Rivoli",
    "PostalCode": "99-778"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/4

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json

{
  "Name": "New name",
  "Description" : "Nice plate",
  "HasDelivery" : true
}

###


POST {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes
Content-Type: application/json

{
 "Name": "Spaghetti",
 "Description": "Best spaghetti eu",
 "Price": 33,
 "Kilocalories": 1050
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes/4

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/3/dishes

###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "@Test12345"
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@gmail.com",
  "password": "@Test12345"
}

GET {{Restaurants.API_HostAddress}}/api/restaurants

###
